const translations={ru:{'nav.skills':'Навыки','nav.experience':'Опыт','hero.title':'Unity Developer','hero.experience':'Опыт работы','hero.portfolio':'Портфолио','hero.status':'Открыт к предложениям','hero.stat1':'года коммерческой разработки','hero.stat2':'C# · Game Development','skills.title':'Технический стек','skills.game':'Разработка игр','skills.architecture':'Архитектура и инструменты','skills.services':'Сервисы и SDKs','experience.title':'Опыт работы','location.cyprus':'Кипр','location.moscow':'Москва','location.saintPetersburg':'Санкт-Петербург','exp.advant.text':'Разработка idle casual / mid-core проектов в команде с геймдизайнером и художником. Отвечал за реализацию игровой логики, механик, систем и интеграций, а также поддержку Firebase и исправление багов.','exp.emehanika.text':'Разработка hyper-casual / casual игр под iOS и Android в команде с художником по собственному ТЗ: от идеи и геймдизайна до реализации и публикации (iGaming).','exp.cat.text':'Разработка mid-core проекта в команде из разработчика, геймдизайнера, художника и продюсера.','summary.title':'Что я умею','summary.1':'Проектировать и поддерживать архитектуру Unity-проектов.','summary.2':'Самостоятельно реализовывать игровые механики и системы.','summary.3':'Интегрировать SDK, Firebase, IAP, рекламу, аналитику и локализацию.','summary.4':'Работать с производительностью, профилированием, багами и релизным циклом.','footer.text':'Unity Developer · C#'},en:{'nav.skills':'Skills','nav.experience':'Experience','hero.title':'Unity Developer','hero.experience':'Experience','hero.portfolio':'Portfolio','hero.status':'Open to opportunities','hero.stat1':'years of commercial development','hero.stat2':'C# · Game Development','skills.title':'Technical stack','skills.game':'Game Development','skills.architecture':'Architecture & Tools','skills.services':'Services & SDKs','experience.title':'Work experience','location.cyprus':'Cyprus','location.moscow':'Moscow','location.saintPetersburg':'Saint Petersburg','exp.advant.text':'Developed idle casual / mid-core projects with a game designer and artist. Responsible for gameplay logic, mechanics, systems and integrations, plus Firebase support and bug fixing.','exp.emehanika.text':'Developed hyper-casual / casual games for iOS and Android with an artist, following an internal specification from concept and game design through implementation and publishing (iGaming).','exp.cat.text':'Developed a mid-core project in a team consisting of a developer, game designer, artist and producer.','summary.title':'What I do','summary.1':'Design and maintain architecture for Unity projects.','summary.2':'Independently implement gameplay mechanics and systems.','summary.3':'Integrate SDKs, Firebase, IAP, ads, analytics and localization.','summary.4':'Work with performance, profiling, bugs and the release cycle.','footer.text':'Unity Developer · C#'}};
const garden={ru:['Разработка игровой логики, механик и систем с нуля и до выпуска проекта.','Самостоятельная реализация новых функций и контента по задачам геймдизайнера.','Выпуск и контроль патчей и обновлений проекта.','Исправление багов, crash\'ей и ANR.','Интеграция и настройка аналитики, рекламных сетей, Firebase и IAP.','Проверка и контроль данных в Firebase и Google Play Console.','Подготовка Android-билдов и сопровождение публикаций.','Поддержка и улучшение архитектуры существующих проектов.','Разработка editor-инструментов для упрощения работы геймдизайнера.','Работа с Git: ведение репозитория, контроль изменений и поддержка актуального состояния проекта.'],en:['Developed gameplay logic, mechanics and systems from initial implementation through release.','Independently implemented new features and content based on game designer tasks.','Prepared and controlled patches and project updates.','Fixed bugs, crashes and ANRs.','Integrated and configured analytics, ad networks, Firebase and IAP.','Checked and maintained data in Firebase and Google Play Console.','Prepared Android builds and supported publishing.','Maintained and improved the architecture of existing projects.','Built editor tools to simplify the game designer workflow.','Worked with Git: repository maintenance, change control and keeping the project in a releasable state.']};
const languageButton=document.getElementById('languageButton');
let language=localStorage.getItem('resume-language')||'ru';
function applyLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=translations[language][el.dataset.i18n];if(value!==undefined)el.innerHTML=value});const list=document.querySelector('[data-i18n-list]');if(list)list.innerHTML=garden[language].map(item=>`<li>${item}</li>`).join('');languageButton.textContent=language==='ru'?'EN':'RU'}
languageButton.addEventListener('click',()=>{language=language==='ru'?'en':'ru';localStorage.setItem('resume-language',language);applyLanguage()});
applyLanguage();

const style=document.createElement('style');
style.textContent='.site-header .header-inner{justify-content:flex-end}.site-header .nav{display:flex;align-items:center;justify-content:flex-end;gap:28px;margin:0}.site-header .nav a,.site-header .language-button{font-size:14px}.site-header .language-button{height:38px;min-width:38px;padding:0 10px;margin:0}';
document.head.appendChild(style);
